<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.cosinuscode.swing</groupId>
        <artifactId>spring-swing-boot-starter-parent</artifactId>
        <version>3.0.3-SNAPSHOT</version>
    </parent>

    <artifactId>spring-swing-example</artifactId>
    <version>1.0-SNAPSHOT</version>

    <properties>
        <application.display.name>Spring Swing Example</application.display.name>
        <application.name>spring-swing-example</application.name>
        <application.description>Spring Swing Example</application.description>
        <application.version>1.0.0</application.version>
        <application.category>Other</application.category>
        <application.class>org.cosinus.swing.example.HelloWorld</application.class>
        <application.home.env.name>SPRING_SWING_EXAMPLE_HOME</application.home.env.name>
        <application.splash.file.name>spring-splash.png</application.splash.file.name>
        <application.splash.progress.arguments>
            -Dsplash-progress -Dsplash-progress-color=56,123,44 -Dsplash-progress-y=245 -Dsplash-progress-x=5
        </application.splash.progress.arguments>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <scope>provided</scope>
        </dependency>
    </dependencies>

</project>
